In [1]:

class Employee: ### 클래스 이름은 대문자로 
    """클래스 정의 """
    def __init__(self, name, dept, age): # 자동 호출되는 생성자 역할
        #self는 현재 생성 중인 객체 자신
        """생성자: 직원의 이름(name), 부서(dept), 나이(age)를 초기화"""
        self.name = name    # 문자열: 직원의 이름
        self.dept = dept    # 문자열: 부서명
        self.age = age      # 정수: 나이

    def show(self):
        """[이름, 나이, 부서] 형식으로 직원 정보를 출력하는 메서드"""
        print(f"[{self.name}, {self.age}, {self.dept}]")

# Employee 클래스의 객체 생성
emp1 = Employee("홍길동", "개발부", 30)# self에 자동 전달 > 생성되는 객체가 self에 전달됨 > __init__()을 자동 호출 > 생성된 객체를 반환
emp2 = Employee("김철수", "마케팅부", 27)

# 직원 정보 출력
emp1.show()  # 출력: [홍길동, 30, 개발부]
emp2.show()  # 출력: [김철수, 27, 마케팅부]

# 클래스 멤버는 기본적으로 public. 
print(f"emp.name = {emp1.name}") # public이다 
emp1.age += 1
print(f"emp.age = {emp1.age}")


[홍길동, 30, 개발부]
[김철수, 27, 마케팅부]
emp.name = 홍길동
emp.age = 31


클래스의 protected, private 지원은 안된다???
- 파이썬은 C++이나 Java처럼 엄격한 접근 제어자(private, protected, public)를 언어 차원에서 강제하지는 않는다
- 기본은 public
- convention(관례: _city), name mangling(이름 변경: __age) 사용으로 접근 제한 효과를 구현


In [2]:
class Person:
    def __init__(self):
        self.name = "홍길동"        # public
        self._city = "서울"        # protected (관례)
        self.__age = 30            # private (name mangling)

    def show(self):
        print(self.name, self._city, self.__age)

p = Person()
p.show()

print(p.name)       # public
print(p._city)      # 밑줄 한개: subclass에서만 사용한다는 개발자의 약속 > 실제 외부 접근 가능
#print(p.__age)      # 밑줄 두개: name mangling > 접근 에러

# 하지만 아래처럼 강제로 접근 가능
print(p._Person__age)  # (name mangling된 실제 이름으로 접근)


홍길동 서울 30
홍길동
서울
30


### 9.2.3 속성 값 수정하기

In [3]:
class Employee:
    def __init__(self, name, age, coding):
        self.__name = name  # private 멤버 > 멤버 이름 앞에 **밑줄 두 개(__)**를 붙이면 private처럼 동작
        self.age = age
        self.coding = coding

emp = Employee("홍길동", 20, 'java')
emp.age += 1 # 클래스 멤버를 클래스 외부에서 변경 가능하나 비추 > 피해야 한다 :: 교재 235, 9.2.3 속성 값 수정하기 
#print(emp.__name)  # 에러 발생 -> name mangle(난도질하다 망가트리다)으로 private 멤버처럼 접근 못하게 하는 것일 뿐이다 >>_classname__name으로 변경한다
print(emp._Employee__name) #_Employee__name 이것이 name mangling이다 역설적으로 이를 통해 접근이 가능하다 
#print(emp)
#help(emp)

홍길동


함수에 객체를 전달시에 변경 가능한가?

In [2]:
import copy # copy 모듈은 Python 표준 라이브러리에 포함된 모듈이므로, Python이 설치된 폴더 안에 있다
##copy.py는 Python 설치 디렉터리 내 lib 폴더에 실제 .py 파일로 존재

class Employee:
    def __init__(self, name, dept, age):
        self.name = name
        self.dept = dept
        self.age = age

    def show(self):
        """[이름, 나이, 부서] 형식으로 직원 정보를 출력하는 메서드"""
        print(f"[{self.name}, {self.age}, {self.dept}]")
    
    #@property # 속성을 읽기 전용으로 만드는 방법
    #def age(self):
    #    return self.age
    
def change_employee(emp): # 참조 변수로 전달하므로 수정 가능하다
    """Employee 객체의 속성을 변경하는 함수"""
    emp.name = "박영희"  # 이름 변경
    emp.age += 1        # 나이 1살 증가
    emp.dept = "인사부"  # 부서 변경
    print("\nchange_employee() 함수내에서:")
    emp.show()

# Employee 객체 생성
emp1 = Employee("홍길동", "개발부", 30)

# 함수 호출 전 상태
print("Before change:")
emp1.show()  # 출력: [홍길동, 30, 개발부]

# Employee 객체를 함수의 인자로 전달
#change_employee(emp1)
change_employee(copy.deepcopy(emp1))
# 함수 호출 후 상태
print("After change:")
emp1.show()  # 출력: [박영희, 31, 인사부]

Before change:
[홍길동, 30, 개발부]

change_employee() 함수내에서:
[박영희, 31, 인사부]
After change:
[홍길동, 30, 개발부]


In [ ]:
# 메소드를 사용한 변경

class Employee:
    def __init__(self, name, dept, age):
        self.name = name
        self.dept = dept
        self.age = age

    def show(self):
        """[이름, 나이, 부서] 형식으로 직원 정보를 출력하는 메서드"""
        print(f"[{self.name}, {self.age}, {self.dept}]")
    
    def change_employee(self, new_dept, age_increment):
        """부서, 나이를 변경하는 메서드"""
        self.dept = new_dept  # 부서 변경
        self.age += age_increment  # 나이 증가

# Employee 객체 생성
emp1 = Employee("홍길동", "개발부", 30)

# 함수 호출 전 상태
print("Before change:")
emp1.show()  # 출력: [홍길동, 30, 개발부]

# Employee 객체의 속성을 클래스 내부 메서드를 사용해 변경
emp1.change_employee("인사부", 1)

# 함수 호출 후 상태
print("After change:")
emp1.show()  # 출력: [박영희, 31, 인사부]

Before change:
[홍길동, 30, 개발부]
After change:
[홍길동, 31, 인사부]


## 9.3 클래스 상속

In [3]:
# Person 클래스 정의
class Person:
    def __init__(self, name, age):
        self.name = name  # 이름
        self.age = age    # 나이
    
    def show(self):
        """Person 클래스의 정보를 출력"""
        print(f"Name: {self.name}, Age: {self.age}")

# Employee 클래스는 Person 클래스를 상속
class Employee(Person):
    def __init__(self, name, age, dept, salary):
        super().__init__(name, age)  # 부모 클래스(Person)의 생성자 호출
        self.dept = dept             # 부서
        self.salary = salary         # 급여
    
    def show(self): #메소드 오버라이드
        """Employee 클래스의 정보를 출력 (Person 클래스의 정보 포함)"""
        #print(f"Name: {self.name}, Age: {self.age}, Dept: {self.dept}, Salary: {self.salary}")
        ## Override
        super().show()  # 부모 클래스의 show() 호출
        print(f"Dept: {self.dept}, Salary: {self.salary}")

# Person 객체 생성
person1 = Person("홍길동", 40)
print("Person info:")
person1.show() 

# Employee 객체 생성
employee1 = Employee("김철수", 30, "개발부", 5000)
print("\nEmployee info:")
employee1.show() 

Person info:
Name: 홍길동, Age: 40

Employee info:
Name: 김철수, Age: 30
Dept: 개발부, Salary: 5000


###클래스 작성 실습::
- Vehicle: 기본 클래스, 색상, 중량, 가격을 속성으로 가짐.> color, weight, price

- Car: Vehicle을 상속하며, 엔진과 탑승자 수를 추가로 가짐. > engine, passengers

- Truck: Vehicle을 상속하며, 바퀴 수와 중량을 추가로 가짐. > wheels, load_weight

In [ ]:
# Vehicle 클래스 정의
class Vehicle:
    def show(self):


# Car 클래스 (Vehicle의 서브클래스)
class Car(Vehicle):
    def show(self):

# Truck 클래스 (Vehicle의 서브클래스)
class Truck(Vehicle):
    def show(self):


# Car 객체 5개 생성
car_list = [
    Car("Red", 1500, 20000, "V6", 4),
    Car("Blue", 1400, 25000, "V8", 5),
    Car("Black", 1600, 30000, "Electric", 4),
    Car("White", 1200, 18000, "Hybrid", 4),
    Car("Green", 1300, 22000, "V6", 5)
]

# Truck 객체 5개 생성
truck_list = [
    Truck("Yellow", 3000, 40000, 8, 10000),
    Truck("Blue", 3200, 45000, 10, 12000),
    Truck("White", 2800, 35000, 6, 8000),
    Truck("Black", 3500, 50000, 12, 15000),
    Truck("Red", 3400, 48000, 10, 14000)
]

# 생성된 객체들 출력 - show()를 사용한 출력 코딩 
print("Cars:")
for car in carList:
    car.


print("\nTrucks:")


### 9.3.3 Override 실습

In [17]:
class Animal:
    def speak(self):
        print("Animal speaks")

class Dog(Animal):
    def speak(self):  # 메서드 오버라이딩
        print("Dog barks")

class Cat(Animal):
    def show(self):
        print(" good")
    def speak(self): ##override
        super().speak() # super.speak() > 자바식 표현 
        print("Cat meows")

# 객체 생성
animal = Animal()
dog = Dog()
cat = Cat()

# 메서드 호출
animal.speak()  # 출력: Animal speaks
dog.speak()     # 출력: Dog barks
cat.speak()     # 출력: Cat meows

Animal speaks
Dog barks
Animal speaks
Cat meows


###has-a 표현

In [18]:
# Dept 클래스 정의
class Dept:
    def __init__(self, name):
        self.name = name  # 부서 이름

    def show(self):
        """부서 정보를 출력"""
        print(f"Department: {self.name}")

# Person 클래스 정의
class Person:
    def __init__(self, name, age):
        self.name = name  # 이름
        self.age = age    # 나이
    
    def show(self):
        """Person 클래스의 정보를 출력"""
        print(f"Name: {self.name}, Age: {self.age}")

# Employee 클래스는 Person 클래스를 상속
class Employee(Person):
    def __init__(self, name, age, dept, salary):
        super().__init__(name, age)  # 부모 클래스(Person)의 생성자 호출
        self.dept = dept             # Dept 객체를 저장
        self.salary = salary         # 급여
    
    def show(self):
        """Employee 클래스의 정보를 출력 (Person 클래스의 정보 포함)"""
        super().show()  # 부모 클래스의 show() 호출
        self.dept.show()  # Dept 객체의 show() 호출
        print(f"Salary: {self.salary}")

# Person 객체 생성
person1 = Person("홍길동", 40)
print("Person info:")
person1.show() 

# Dept 객체 생성
dept1 = Dept("개발부")

# Employee 객체 생성 (Dept 객체를 포함)
employee1 = Employee("김철수", 30, dept1, 5000)
print("\nEmployee info:")
employee1.show()

Person info:
Name: 홍길동, Age: 40

Employee info:
Name: 김철수, Age: 30
Department: 개발부
Salary: 5000


- 특수 메소드: 더블언더 메소드(dunder method)> 매직 메소드

-  던더메소드 __str__() 메서드는 객체를 문자열로 표현할 때 자동으로 호출되는 내장 메서드

In [ ]:
class Person:
    def __init__(self, name, age):# 객체 생성 시 __init__() 자동 호출
        self.name = name
        self.age = age
# __str__과 __repr__은 파이썬 객체를 문자열로 표현할 때 사용하는 특별 메서드(던더 메서드)이며, 
# 비슷해 보이지만 용도와 목적이 다르다.
    def __str__(self):
        return f'Person(이름: {self.name}, 나이: {self.age})'
    
    def __repr__(self): #representation (표현)
         ### 객체를 개발자용 또는 디버깅용 문자열로 표현할 수 있게 하는 메서드
        return f"Person('{self.name}', {self.age})"


class Department:
    def __init__(self, name):# 객체 생성 시 __init__() 자동 호출
        self.name = name

    def __str__(self):
        return f'Department(부서명: {self.name})'


class Employee(Person):
    def __init__(self, name, age, department):
        super().__init__(name, age)
        self.department = department

    def __str__(self):
        #super().__str__()
        #return f'Employee(이름: {self.name}, 나이: {self.age}, 부서: {self.department})'
        return f'{super().__str__()} Employee(부서: {self.department})'


# 부서 생성
dept1 = Department("영업")
dept2 = Department("코딩")
dept3 = Department("설계")

# Employee 객체 5개 생성
employees = [
    Employee("홍길동", 30, dept1),
    Employee("강감찬", 25, dept2),
    Employee("을지문덕", 28, dept3),
    Employee("김유신", 35, dept1),
    Employee("계백", 27, dept2)
]

# 생성된 Employee 객체 출력
for employee in employees:
    s = str(employee)
    print(f"던더 메소드 호출 : {s}") # __str__() 호출
    print(employee) # __str__() 호출
   
    print(repr(employee)) # __repr__() 호출

던더 메소드 호출 : Person(이름: 홍길동, 나이: 30) Employee(부서: Department(부서명: 영업))
Person(이름: 홍길동, 나이: 30) Employee(부서: Department(부서명: 영업))
Person('홍길동', 30)
던더 메소드 호출 : Person(이름: 강감찬, 나이: 25) Employee(부서: Department(부서명: 코딩))
Person(이름: 강감찬, 나이: 25) Employee(부서: Department(부서명: 코딩))
Person('강감찬', 25)
던더 메소드 호출 : Person(이름: 을지문덕, 나이: 28) Employee(부서: Department(부서명: 설계))
Person(이름: 을지문덕, 나이: 28) Employee(부서: Department(부서명: 설계))
Person('을지문덕', 28)
던더 메소드 호출 : Person(이름: 김유신, 나이: 35) Employee(부서: Department(부서명: 영업))
Person(이름: 김유신, 나이: 35) Employee(부서: Department(부서명: 영업))
Person('김유신', 35)
던더 메소드 호출 : Person(이름: 계백, 나이: 27) Employee(부서: Department(부서명: 코딩))
Person(이름: 계백, 나이: 27) Employee(부서: Department(부서명: 코딩))
Person('계백', 27)


print(p) → __str__ 우선, 없으면 __repr__

리스트, 딕셔너리 출력 시 → __repr__ 사용

디버깅, 로그 출력 → __repr__이 더 정확하고 유용함

In [4]:
people = [Person("김유신", 25), Person("이순신", 40)]
print(people)  # __repr__로 표현된 결과
# [Person('김유신', 25), Person('이순신', 40)]


[Person('김유신', 25), Person('이순신', 40)]


더블 언더 메서드(dunder method)는 파이썬에서 특별한 의미를 가지는 메서드
객체의 행동을 정의하는 데 사용. 

__str__, __repr__, __eq__, __len__ 등

In [21]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def __str__(self):
        return f'Person(Name: {self.name}, Age: {self.age})'

    def __repr__(self):
        return f'Person(name={self.name!r}, age={self.age!r})'

    def __eq__(self, other):
        if isinstance(other, Person):
            return self.name == other.name and self.age == other.age
        return False

    def __len__(self):
        return len(self.name) + len(str(self.age))  # 이름과 나이의 길이 합


class Department:
    def __init__(self, name):
        self.name = name

    def __str__(self):
        return f'Department(Name: {self.name})'

    def __repr__(self):
        return f'Department(name={self.name!r})'


class Employee(Person):
    def __init__(self, name, age, department):
        super().__init__(name, age)
        self.department = department

    def __str__(self):
        return f'Employee(Name: {self.name}, Age: {self.age}, Department: {self.department})'

    def __repr__(self):
        return f'Employee(name={self.name!r}, age={self.age!r}, department={self.department!r})'

    def __eq__(self, other):
        if isinstance(other, Employee):
            return super().__eq__(other) and self.department == other.department
        return False

    def __len__(self):
        return len(self.name) + len(str(self.age)) + len(self.department.name)  # 이름, 나이, 부서의 길이 합


# 부서 생성
dept1 = Department("개발")
dept2 = Department("코딩")

# Employee 객체 2개 생성
emp1 = Employee("홍길동", 30, dept1)
emp2 = Employee("이광수", 25, dept2)

# 객체 출력
print(emp1)  # __str__ 사용
print(repr(emp2))  # __repr__ 사용

# 객체 비교
print(emp1 == emp2)  # __eq__ 사용

# Person 객체와 비교
person1 = Person("강감찬", 30)
print(emp1 == person1)  # False (다른 클래스 비교)
print(emp1 == emp2)  # False (다른 클래스 비교)
# 길이 출력
print(len(emp1))  # Employee 객체의 길이
print(len(person1))  # Employee 객체의 길이

Employee(Name: 홍길동, Age: 30, Department: Department(Name: 개발))
Employee(name='이광수', age=25, department=Department(name='코딩'))
False
False
False
7
5


### 객체를 함수처럼 호출할 수 있게 하는 def __call__()

### 객체의 자동 소멸 시점: 참조 카운트가 0이 될 때

파이썬은 **가비지 컬렉션(Garbage Collection)**을 사용하여

사용되지 않는 객체를 자동으로 제거

In [ ]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def __str__(self):
        return f'Person(Name: {self.name}, Age: {self.age})'

    def __repr__(self):
        return f'Person(name={self.name!r}, age={self.age!r})'

    def __eq__(self, other):
        if isinstance(other, Person):
            return self.name == other.name and self.age == other.age
        return False

    def __len__(self):
        return len(self.name) + len(str(self.age))


class Department:
    def __init__(self, name):
        self.name = name

    def __str__(self):
        return f'Department(Name: {self.name})'

    def __repr__(self):
        return f'Department(name={self.name!r})'


class Employee(Person):
    def __init__(self, name, age, department):
        super().__init__(name, age)
        self.department = department

    def __str__(self):
        return f'Employee(Name: {self.name}, Age: {self.age}, Department: {self.department})'

    def __repr__(self):
        return f'Employee(name={self.name!r}, age={self.age!r}, department={self.department!r})'

    def __eq__(self, other):
        if isinstance(other, Employee):
            return super().__eq__(other) and self.department == other.department
        return False

    def __len__(self):
        return len(self.name) + len(str(self.age)) + len(self.department.name)

    def __call__(self, new_age): # 객체를 함수처럼 호출할 수 있게 만들어주는 특별한 메서드
        self.age = new_age  # 나이를 업데이트하는 메서드
    
    def __del__(self):
        print("소멸 {}".format(self.name)) # __del__() 메서드는 객체가 소멸될 때 자동으로 호출되며, 이 메서드 내부에 특정 작업을 수행할 수 있음을 보이는 것



# 부서 생성
dept1 = Department("개발")
dept2 = Department("코딩")

# Employee 객체 2개 생성
emp1 = Employee("홍길동", 30, dept1)
emp2 = Employee("이광수", 25, dept2)

# 객체 출력
print(emp1)  # __str__ 사용
print(repr(emp2))  # __repr__ 사용

# 객체 비교
print(emp1 == emp2)  # __eq__ 사용

# Person 객체와 비교
person1 = Person("강감찬", 30)
print(emp1 == person1)  # emp1의 클래스인 Employee의 __eq__() 메서드가 호출

# 길이 출력
print(len(emp1))  # Employee 객체의 길이
print(len(emp2))  # Employee 객체의 길이

# __call__ 메서드 사용
print(f"나이 변경전: {emp1}")
emp1(35)  # 객체 내부에 __call__()이 정의되어 있으면, obj() 문법이 자동으로 obj.__call__()을 호출
## 머신러닝 모델 객체를 model(input)처럼 호출
print(f"나이 변경후: {emp1}")

del emp1

if (isinstance(emp2, Employee)):
    print(type(emp2))


Employee(Name: 홍길동, Age: 30, Department: Department(Name: 개발))
Employee(name='이광수', age=25, department=Department(name='코딩'))
False
False
7
7
나이 변경전: Employee(Name: 홍길동, Age: 30, Department: Department(Name: 개발))
나이 변경후: Employee(Name: 홍길동, Age: 35, Department: Department(Name: 개발))
소멸 홍길동
<class '__main__.Employee'>


## 9.4 클래스 import > 교재 249페이지를 사용

In [23]:
from car import Car

my_used_car = Car('subaru', 'outback', 2019)
print(my_used_car.get_descriptive_name())

my_used_car.update_odometer(23_500)
my_used_car.read_odometer()

my_used_car.increment_odometer(100)
my_used_car.read_odometer()



2019 Subaru Outback
This car has 23500 miles on it.
This car has 23600 miles on it.


In [24]:
# 교재 P250 코드 사용
from electric_car import ElectricCar, Car

my_leaf = ElectricCar('nissan', 'leaf', 2024)
print(my_leaf.get_descriptive_name())
my_leaf.battery.describe_battery()
my_leaf.battery.get_range()

mycar = Car('kia', 'k7', 2024)
print(mycar.get_descriptive_name())

2024 Nissan Leaf
This car has a 40-kWh battery.
This car can go about 150 miles on a full charge.
2024 Kia K7


파이썬 표준 라이브러리: 교재 256페이지 

In [ ]:
import random # random.py라는 파일로 구현
## C:\Users\<사용자명>\AppData\Local\Programs\Python\Python<버전>\Lib\random.py


# 행렬의 크기 설정
rows = 3  # 행의 개수
cols = 4  # 열의 개수

# 0과 1 사이의 난수로 2차원 행렬 생성
matrix = [[random.uniform(0, 1) for _ in range(cols)] for _ in range(rows)]

# 결과 출력
print("2차원 행렬 (0과 1 사이의 난수):")
for row in matrix:
    print(row)

# 정수 범위의 난수 생성 (예: 0부터 10까지)
int_matrix = [[random.randint(0, 9) for _ in range(cols)] for _ in range(rows)]

print("\n2차원 행렬 (정수 난수, 0부터 9까지):")
for row in int_matrix:
    print(row)

2차원 행렬 (0과 1 사이의 난수):
[0.08257767589640708, 0.23660512257894162, 0.3052433334479018, 0.7978958419969273]
[0.1228831782553359, 0.2992135295609466, 0.9151635091314576, 0.8641707075318046]
[0.9681642055357077, 0.06142898260425789, 0.851971204164697, 0.3330992311491665]

2차원 행렬 (정수 난수, 0부터 9까지):
[5, 8, 8, 9]
[7, 9, 7, 2]
[1, 8, 1, 3]


In [5]:
import random
print(random.__file__)


c:\Users\bhhong\AppData\Local\Programs\Python\Python39\lib\random.py


In [6]:
import numpy
print(numpy.__file__)


c:\Users\bhhong\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\__init__.py


- site-packages 폴더는 pip로 설치한 외부 패키지들이 저장되는 폴더
- numpy는 Python 표준 라이브러리에는 포함되지 않는다
- pip install numpy 명령어로 설치한 **외부 패키지 (third-party library)**

In [7]:
#설치 여부 확인
!pip show numpy


Name: numpy
Version: 1.26.4
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: Copyright (c) 2005-2023, NumPy Developers.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

    * Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.

    * Redistributions in binary form must reproduce the above
       copyright notice, this list of conditions and the following
       disclaimer in the documentation and/or other materials provided
       with the distribution.

    * Neither the name of the NumPy Developers nor the names of any
       contributors may be used to endorse or promote products derived
       from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYR

In [28]:
import numpy as np

# 행렬의 크기 설정
rows = 3  # 행의 개수
cols = 4  # 열의 개수

# 0과 1 사이의 난수로 2차원 행렬 생성
matrix = np.random.rand(rows, cols)

# 결과 출력
print("2차원 행렬 (0과 1 사이의 난수):")
print(matrix)

# 정수 범위의 난수 생성 (예: 0부터 10까지)
int_matrix = np.random.randint(0, 10, size=(rows, cols))

print("\n2차원 행렬 (정수 난수, 0부터 10까지):")
print(int_matrix)

2차원 행렬 (0과 1 사이의 난수):
[[0.71636029 0.84883612 0.31270594 0.83986828]
 [0.51934875 0.31424073 0.26160045 0.95511905]
 [0.40005135 0.00183565 0.58628794 0.15435145]]

2차원 행렬 (정수 난수, 0부터 10까지):
[[7 6 0 8]
 [1 0 0 0]
 [6 0 2 9]]


In [30]:
from random import choice
lst = ['good','nice','beauty','follow','go','come','java']
for _ in range(5):
    rnd = choice(lst)
    print(rnd)


good
java
java
good
go


클래스 변수와 클래스  메소드 사용 

In [32]:
# Dept 클래스 정의
class Dept:
    total_departments = 0  # 클래스 변수

    def __init__(self, name):
        self.name = name  # 부서 이름
        Dept.total_departments += 1  # 부서가 생성될 때마다 클래스 변수를 증가
    
    def show(self):
        """부서 정보를 출력"""
        print(f"부서명: {self.name}")

    @classmethod
    def show_total_departments(cls):
        """전체 부서 수를 출력하는 클래스 메소드"""
        print(f"부서갯수: {cls.total_departments}") #cls는 클래스 메서드가 호출되는 클래스 자체를 가리킨다


# Person 클래스 정의
class Person:
    total_persons = 0  # 클래스 변수

    def __init__(self, name, age):
        self.name = name  # 이름
        self.age = age    # 나이
        Person.total_persons += 1  # Person 객체가 생성될 때마다 클래스 변수를 증가
    
    def show(self):
        """Person 클래스의 정보를 출력"""
        print(f"이름: {self.name}, 나이: {self.age}")

    @classmethod
    def show_total_persons(cls):
        """전체 사람 수를 출력하는 클래스 메소드"""
        print(f"사람수: {cls.total_persons}")


# Employee 클래스는 Person 클래스를 상속
class Employee(Person):
    total_employees = 0  # 클래스 변수

    def __init__(self, name, age, dept, salary):
        super().__init__(name, age)  # 부모 클래스(Person)의 생성자 호출
        self.dept = dept             # Dept 객체를 저장
        self.salary = salary         # 급여
        Employee.total_employees += 1  # Employee 객체가 생성될 때마다 클래스 변수를 증가
    
    def show(self):
        """Employee 클래스의 정보를 출력 (Person 클래스의 정보 포함)"""
        super().show()  # 부모 클래스의 show() 호출
        self.dept.show()  # Dept 객체의 show() 호출
        print(f"월급: {self.salary}")

    @classmethod
    def show_total_employees(cls):
        """전체 직원 수를 출력하는 클래스 메소드"""
        print(f"직원수: {cls.total_employees}")

# 클래스 메소드 호출
Dept.show_total_departments() #cls는 Dept를 받는다 
Person.show_total_persons()
Employee.show_total_employees()

# 예시 사용
dept1 = Dept("설계")
dept2 = Dept("코딩")

emp1 = Employee("홍길동", 30, dept1, 50000)
emp2 = Employee("강감찬", 25, dept2, 60000)

# 각 클래스의 인스턴스 메소드 호출
emp1.show()
emp2.show()

# 클래스 메소드 호출
Dept.show_total_departments() #cls는 Dept를 받는다 
Person.show_total_persons()
Employee.show_total_employees()

부서갯수: 0
사람수: 0
직원수: 0
이름: 홍길동, 나이: 30
부서명: 설계
월급: 50000
이름: 강감찬, 나이: 25
부서명: 코딩
월급: 60000
부서갯수: 2
사람수: 2
직원수: 2


리스트와 튜플의 unpacking 사용

In [ ]:
a=[1,2,3]
b=[4,5,6]
mylist = [*a,*b] # *는 iterable 객체를 unpacking하는 의미 
print(mylist)
#x,y,z = *a ## 문법 오류
#x,y,z = (*a) ##
x,y,z = tuple(a)
print(x,y,z)


[1, 2, 3, 4, 5, 6]
1 2 3
(11, 22, 33)


### 파이썬 사용자 정의 컨테이너 타입

In [ ]:
class MyList:
    def __init__(self, initial_data):
        # 초기 데이터를 리스트로 저장
        self.data = list(initial_data)
    
    # 인덱스 접근을 위한 __getitem__ 메서드 구현
    def __getitem__(self, index): ### 머신러닝에서 사용됨 
        print("__getitem__() 호출됨")
        return self.data[index]
    
    # 인덱스를 통해 값을 설정하는 __setitem__ 메서드 구현
    def __setitem__(self, index, value):
        print("__setitem__() 호출됨")
        self.data[index] = value
    
    # 인덱스를 통해 값을 삭제하는 __delitem__ 메서드 구현
    def __delitem__(self, index):
        del self.data[index]
    
    # len() 함수가 작동하도록 __len__ 메서드 구현
    def __len__(self):
        return len(self.data)
    
    # 출력할 때 인스턴스의 리스트 데이터를 보여주기 위한 __repr__ 메서드 구현
    def __repr__(self):
        print("__repr__() 호출됨")
        return repr(self.data)

# 사용 예시
my_list = MyList([1, 2, 3, 4])
print('---인덱스 사용---')
# 배열처럼 접근
print(my_list[0])  # 1 - def __getitem__(self, index):

print('---변경---')
# 배열처럼 값 변경
my_list[1] = 10 # def __setitem__(self, index, value):
print('---출력---')
print(my_list)  # [1, 10, 3, 4]

print('---삭제---')
# 배열처럼 값 삭제
del my_list[2]
print(my_list)  # [1, 10, 4]

# 배열의 길이 확인
print(len(my_list))  # 3

---인덱스 사용---
__getitem__() 호출됨
1
---변경---
__setitem__() 호출됨
---출력---
__repr__() 호출됨
[1, 10, 3, 4]
---삭제---
__repr__() 호출됨
[1, 10, 4]
3


In [11]:
class MyDict:
    def __init__(self):
        self.data = {}

    def __getitem__(self, key):
        return self.data[key]

    def __setitem__(self, key, value):
        self.data[key] = value

    def __delitem__(self, key):
        del self.data[key]

    def __repr__(self):
        return repr(self.data)

# MyDict 객체 생성
d = MyDict()

# __setitem__ 호출 예제: 항목 추가
d['name'] = 'Alice'   # → d.__setitem__('name', 'Alice')가 호출됨
d['age'] = 30         # → d.__setitem__('age', 30)

# __getitem__ 호출 예제: 항목 조회
print(d['name'])      # → d.__getitem__('name') 호출됨 → 출력: Alice
print(d['age'])       # → d.__getitem__('age') 호출됨 → 출력: 30

# __repr__ 호출 예제: 객체 전체 출력
print(d)              # → d.__repr__() 호출됨 → 출력: {'name': 'Alice', 'age': 30}

# __delitem__ 호출 예제: 항목 삭제
del d['age']          # → d.__delitem__('age') 호출됨

# 다시 객체 출력 (__repr__)
print(d)              # 출력: {'name': 'Alice'}


Alice
30
{'name': 'Alice', 'age': 30}
{'name': 'Alice'}
